version: '3.9'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:4.2
    hostname: localhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Aa123456
      - MONGO_INITDB_DATABASE=GYM_mongodb
    volumes:
      - mongo-data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
       test: echo 'db.runCommand("ping").ok'
       interval: 10s
       timeout: 10s
       retries: 5
  
  # nginx:
    # build:
      # context: .
      # dockerfile: nginx.dockerfile
    # ports:
      # - 80:80
      # - 443:443
    # volumes:
      # - ./templates:/usr/share/nginx/html
    # depends_on:
      # - flask-app
volumes:
  mongo-data:


